
name: Image Processing with OpenCV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install opencv-python numpy pillow requests

      - name: Download Image
        run: |
          wget -O original.jpg "https://image-us.samsung.com/us/smartphones/galaxy-s25/Gallery/PA1/PA1-01-Navy-1600x1200.jpg"

      - name: Run Image Processing Script
        run: python process_image.py

      - name: Upload Processed Image
        uses: actions/upload-artifact@v3
        with:
          name: processed-image
          path: processed.jpg
