name: Convert HTML to Mobile Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert-html-to-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install wkhtmltoimage dependencies
      - name: Install wkhtmltoimage
        run: |
          sudo apt update
          sudo apt install wkhtmltopdf -y

      # Convert HTML to Mobile Image (using mobile viewport)
      - name: Convert HTML to Mobile Image
        run: |
          wkhtmltoimage --width 375 --height 667 --disable-smart-width --zoom 1.5 --javascript-delay 1000 index.html full_output.png

      # Upload the resulting image as an artifact
      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-image
          path: full_output.png
