name: Convert HTML to Mobile Image

on: [push]

jobs:
  convert-html-to-mobile-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wkhtmltopdf imagemagick  # Install both

      - name: Convert HTML to Mobile Image
        run: |
          wkhtmltoimage --viewport-size 375x667 --width 375 --height 667 --zoom 1.5 index.html full_output.png
          
      - name: Crop Mobile Image
        run: convert full_output.png -crop 375x600+0+50 cropped_output.png  
        # Crops 375x600 from (x=0, y=50) to remove unnecessary parts

      - name: Upload Cropped Image
        uses: actions/upload-artifact@v4
        with:
          name: html-mobile-image
          path: cropped_output.png
